### PR TITLE
change @return self to @return $this

### PR DESCRIPTION
**Pull request by pavarnos**
for #86

### CODE REVIEW

**Comment by pmjones** [comment]
Nice. Thanks!

**Comment by pavarnos** [comment]
packagist not updating https://packagist.org/packages/aura/sqlquery#2.x-dev. Do you have a github service hook enabled?

**Comment by harikt** [comment]
@pavarnos yes we have everything enabled. May be packagist.json is not updated by the cron of their server. If you are still having trouble let me know.

**Comment by pmjones** [comment]
I ended up pushing the "update" button at Packagist. Not sure why the hook didn't activate.

**Pull request merged**
