### PR TITLE
Add ignore() method to common Insert class

### PR DESCRIPTION
**Pull request by maximTarleckiy**
https://github.com/auraphp/Aura.SqlQuery/issues/172

### CODE REVIEW

**Comment by harikt** [comment]
I agree with you. It looks `orIgnore` seems to be used inside update also.

Only question here is do we want to use `$inser->ignore()` or `$inser->orIgnore()`.

**Review by koriym — APPROVED** [review]

**Comment by NaokiTsuchiya** [comment]
LGTM

**Comment by harikt** [comment]
@koriym , @NaokiTsuchiya  please do make sure other methods are also changed.

**Comment by koriym** [comment]
@harikt Sorry we missed it.

**Comment by harikt** [comment]
As we move to 3.x BC is not an issue. But I wish we could address using ignore or ignoreOr

**Comment by koriym** [comment]
@harikt `orIgnore` method marked `@deprecated`?

**Comment by harikt** [comment]
That is the change in this PR. But I doubt about it.

**Pull request merged**
