### PR TITLE
Add getStatement method to QueryInterface

### PR DESCRIPTION
**Pull request by thinkspill**
Since all methods now have getStatement since 2.3, add to QueryInterface to help with IDE autocompletion.

### CODE REVIEW

**Comment by harikt** [comment]
You cannot change the interface which is BC break. Wait for 3.x for it is almost there.

**Comment by thinkspill** [comment]
Ah, thanks very much. Waiting patiently. ;)

**Comment by harikt** [comment]
:) .

**Comment by pmjones** [comment]
As @harikt notes, we can't change an Interface without breaking BC. However, adding `@method` hints to the DocBlock might cause the IDE to "see" the method. You want to try that out @thinkspill ? Cf. http://phpdoc.org/docs/latest/references/phpdoc/tags/method.html

**Pull request closed without merging**
