### PR TITLE
3.x quoter

### PR DESCRIPTION
**Pull request by pmjones**
This PR creates separate quoter classes for each driver (notably mysql and sqlsrv).

@harikt @pavarnos Thoughts?

### CODE REVIEW

**Comment by harikt** [comment]
@pmjones 

Thank you for pinging.

I am not sure what advantage do you see in moving to a separate class than passing the string?

**Comment by pavarnos** [comment]
@harikt it removes db specific config from the generic QueryFactory class https://github.com/auraphp/Aura.SqlQuery/pull/132/files#diff-f4d2c86a7d03f40d9533ddaca828a28fL47 into the db specific driver directory, which is an improvement in clarity. It makes the quoter re-usable too (eg in Aura.Sql?).

@pmjones how is the test coverage? I can't seem to find it...

**Comment by pmjones** [comment]
@harikt As @pavarnos notes, it's "better form" than before, but not in any way functionally critical.

@pavarnos Test is at https://github.com/auraphp/Aura.SqlQuery/pull/132/files#diff-c13b8f7f14b2d2fbc0552d98128d064f and coverage should be the same as before (i.e. 100%); the db-specific quoters only modify properties, not methods. Cf. https://scrutinizer-ci.com/g/auraphp/Aura.SqlQuery/?branch=3.x

Other thoughts?

**Comment by harikt** [comment]
@pmjones @pavarnos thank you.

The quoter is actually introduced in https://github.com/auraphp/Aura.Sql/pull/153 .

So I doubt about it.

**Comment by pavarnos** [comment]
Thanks. Temporary blindness: I cannot find the coverage report / percentage?

**Comment by pmjones** [comment]
@harikt So is that a "yes" or a "no" on this PR?

@pavarnos At the Scrutinizer link, on the right, under "Badges", it shows 100%.

**Comment by harikt** [comment]
@pmjones I was answering to @pavarnos 

> It makes the quoter re-usable too (eg in Aura.Sql?).

The quoter is actually introduced in auraphp/Aura.Sql#153 .

So I doubt about it.

Probably the Quoter in that case can be moved out. But that may break what we advertise, but less things being duplicated.

**Comment by pmjones** [comment]
@harikt Ah right. Yes, the quoter in Sql is much more limited.

@harikt @pavarnos Just so that we can either merge or close this PR, and I back to the "actual plan" laid out in #108 , give me "go" or "no-go" and I'll work from there.

**Comment by harikt** [comment]
@pmjones I am :+1:  . So "go" .

**Comment by pavarnos** [comment]
good with me

**Comment by pmjones** [comment]
Thanks folks. Back to #108 !

**Pull request merged**
