### PR TITLE
Updated readme to match implementation.

### PR DESCRIPTION
**Pull request by jakeasmith**
Select::from() expects a string, not an array.

### CODE REVIEW

**Comment by harikt** [comment]
I am also seeing some other places to be fixed for the method `from`.

**Comment by jakeasmith** [comment]
Amended. Good eye :beers:

**Comment by harikt** [comment]
@pmjones good to merge.

**Comment by harikt** [comment]
I am merging this.

**Comment by harikt** [comment]
Thank you @jakeasmith

**Pull request merged**
